CREATE TABLE WEB(URL VARCHAR2(200) PRIMARY KEY,
                TITULO VARCHAR2(40),
                DESCRIP VARCHAR2(50),
                VALOR NUMERIC );

CREATE TABLE VISITAS(INDICE NUMERIC PRIMARY KEY,
                    FECHA DATE,
                    TIEMPO VARCHAR2(20),
                    URL VARCHAR2(200),
        FOREIGN KEY(URL) REFERENCES WEB(URL));

CREATE TABLE CATEGORIA(NOMBRECAT VARCHAR2(20) PRIMARY KEY,
                    NUMPAG NUMERIC);

CREATE TABLE ASIGNADA(NOMBRECAT VARCHAR2(20),
                    URL VARCHAR2(200),
                    FECHA DATE,
        FOREIGN KEY(NOMBRECAT) REFERENCES CATEGORIA(NOMBRECAT),
        FOREIGN KEY(URL) REFERENCES WEB(URL));
