CREATE TABLE RUTA(CODIGO VARCHAR2(20) PRIMARY KEY,
                KM NUMERIC,
                DESDE VARCHAR2(20),
                HASTA VARCHAR2(20) );

CREATE TABLE BUS(MATRICULA VARCHAR2(20) PRIMARY KEY,
                MODELO VARCHAR2(20),
                CAPACIDAD NUMERIC,
                CONDUCTOR VARCHAR2(20),
                CODIGO VARCHAR2(20),
        FOREIGN KEY(CODIGO) REFERENCES RUTA(CODIGO));

CREATE TABLE CIUDAD(NOMBRE VARCHAR2(20) PRIMARY KEY,
                    DIRECCION VARCHAR2(50),
                    TELEFONO VARCHAR2(10));

CREATE TABLE PARA_EN(CODIGO VARCHAR2(20),
                    NOMBRE VARCHAR2(20),
                    NORDEN NUMERIC,
        FOREIGN KEY(CODIGO) REFERENCES RUTA(CODIGO),
        FOREIGN KEY(NOMBRE) REFERENCES CIUDAD(NOMBRE));
