CREATE TABLE ESPECIES(NOMBRESP VARCHAR2(20) PRIMARY KEY,
                    FLORACION VARCHAR2(20),
                    PLANTACION VARCHAR2(20),
                    SUELO VARCHAR2(20),
                    EXPOISICIN VARCHAR2(20));

CREATE TABLE PEDIDOS(NUMPED NUMERIC PRIMARY KEY,
                    FECHA DATE,
                    IMPORTE NUMERIC);

CREATE TABLE FLORES(CODIGO VARCHAR2(20) PRIMARY KEY,
                    NOMBREFL VARCHAR2(20),
                    PRECIO NUMERIC,
                    NOMBRESP VARCHAR2(20),
        FOREIGN KEY(NOMBRESP) REFERENCES ESPECIES(NOMBRESP));

CREATE TABLE CONTIENE(NUMPED NUMERIC,
                    CODIGO VARCHAR2(20),
                    CANTIDAD NUMERIC,
        FOREIGN KEY(NUMPED) REFERENCES PEDIDOS(NUMPED),
        FOREIGN KEY(CODIGO) REFERENCES FLORES(CODIGO));
