CREATE TABLE USUARIO(NOMBREU VARCHAR2(20) PRIMARY KEY,
                    PASSWD VARCHAR2(20),
                    EMAIL VARCHAR2(40) );

CREATE TABLE FOTO(URL VARCHAR2(200) PRIMARY KEY,
                NOMBREF VARCHAR2(20),
                TIPO VARCHAR2(10),
                TAMANO NUMERIC,
                RESOLUCION VARCHAR2(10),
                NOMBREU VARCHAR2(20),
        FOREIGN KEY(NOMBREU) REFERENCES USUARIO(NOMBREU));

CREATE TABLE ETIQUETA(NOMBREET VARCHAR2(20) PRIMARY KEY,
                    TOTALFOTOS NUMERIC);

CREATE TABLE ASIGNADA(URL VARCHAR2(200),
                    NOMBREET VARCHAR2(20),
                    SUGERIDA_POR VARCHAR2(30),
        FOREIGN KEY(URL) REFERENCES FOTO(URL),
        FOREIGN KEY(NOMBREET) REFERENCES ETIQUETA(NOMBREET));
