--Tabla Ruta
INSERT INTO RUTA( CODIGO, KM, DESDE, HASTA)
VALUES ('XX1', 10, 'Un lugar', 'El otro');

INSERT INTO RUTA( CODIGO, KM, DESDE, HASTA)
VALUES ('XX2', 4, 'Otro lugar', 'Donde sea');

INSERT INTO RUTA( CODIGO, KM, DESDE, HASTA)
VALUES ('XX3', 15, 'Un sitio', 'Hasta el lugar');


--Tabla Bus
INSERT INTO BUS(MATRICULA, MODELO, CAPACIDAD, CONDUCTOR, CODIGO)
VALUES ('12312301', 'Alpha', 20, 'Pedro Mir', 'XX1');

INSERT INTO BUS(MATRICULA, MODELO, CAPACIDAD, CONDUCTOR, CODIGO)
VALUES ('12312302', 'Beta', 30, 'Isidro News', 'XX2');

INSERT INTO BUS(MATRICULA, MODELO, CAPACIDAD, CONDUCTOR, CODIGO)
VALUES ('12312303', 'Peta', 25, 'Lucker Nether', 'XX3');


--Tabla Ciudad
INSERT INTO CIUDAD(NOMBRE, DIRECCION, TELEFONO)
VALUES ('Santo Domingo', 'Metiendote por un sitio por ahi', '8082322323');

INSERT INTO CIUDAD(NOMBRE, DIRECCION, TELEFONO)
VALUES ('Santiago', 'Metiendote por otro sitio por ahi', '8082323333');

INSERT INTO CIUDAD(NOMBRE, DIRECCION, TELEFONO)
VALUES ('La Romana', 'Brincando mucho', '8082222323');


--Tabla Para_en
INSERT INTO PARA_EN (CODIGO, NOMBRE, NORDEN)
VALUES ('XX1', 'Santo Domingo', 23);

INSERT INTO PARA_EN (CODIGO, NOMBRE, NORDEN)
VALUES ('XX2', 'Santiago', 33);

INSERT INTO PARA_EN (CODIGO, NOMBRE, NORDEN)
VALUES ('XX1', 'La Romana', 13);
